name 'mycorp_resources'
maintainer 'Tim Sith'
maintainer_email 'tim@mycorp.com'
license 'All Rights Reserved'
description 'A cookbook containing resources specific to MyCorp'
version '0.1.0'
chef_version '>= 13.0'
